/*
 * A lexical scanner generated by flex
 * vile:lexmode
 *
 * Scanner skeleton version:
 * @Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp @
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_LOWER_VERSION 4
#define YY_FLEX_PATCH_VERSION 20210808

#include <stdio.h>

/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif

#ifdef __cplusplus

#include <stdlib.h>

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else /* ! __cplusplus */

#if __STDC__

#define YY_USE_CONST

#endif /* __STDC__ */
#endif /* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin)

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if (condition_holds)
 *		yyless(5);
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
	    { \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
	    } \
	while (0)

#define unput(c) yyunput(c, yytext_ptr)

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#define YY_SIZE_T size_t
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
#ifndef YY_SIZE_T
#define YY_SIZE_T unsigned
#endif

typedef YY_SIZE_T yy_size_t;

struct yy_buffer_state {
    FILE *yy_input_file;

    char *yy_ch_buf;		/* input buffer */
    char *yy_buf_pos;		/* current position in input buffer */

    /* Size of input buffer in bytes, not including room for EOB
     * characters.
     */
    yy_size_t yy_buf_size;

    /* Number of characters read into yy_ch_buf, not including EOB
     * characters.
     */
    int yy_n_chars;

    /* Whether we "own" the buffer - i.e., we know we created it,
     * and can realloc() it to grow it, and should free() it to
     * delete it.
     */
    int yy_is_our_buffer;

    /* Whether this is an "interactive" input source; if so, and
     * if we're using stdio for input, then we want to use getc()
     * instead of fread(), to make sure we stop fetching input after
     * each newline.
     */
    int yy_is_interactive;

    /* Whether we're considered to be at the beginning of a line.
     * If so, '^' rules will be active on the next match, otherwise
     * not.
     */
    int yy_at_bol;

    /* Whether to try to fill the input buffer when we reach the
     * end of it.
     */
    int yy_fill_buffer;

    int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
    /* When an EOF's been seen but there's still some text to process
     * then we mark the buffer as YY_EOF_PENDING, to indicate that we
     * shouldn't try reading from the input source any more.  We might
     * still have a bunch of tokens to match, though, because of
     * possible backing-up.
     *
     * When we actually see the EOF, we change the status to "new"
     * (via yyrestart()), so that the user can continue scanning by
     * just pointing yyin at a new input file.
     */
#define YY_BUFFER_EOF_PENDING 2
};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */

int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart(FILE *input_file);

void yy_switch_to_buffer(YY_BUFFER_STATE new_buffer);
void yy_load_buffer_state(void);
YY_BUFFER_STATE yy_create_buffer(FILE *file, int size);
void yy_delete_buffer(YY_BUFFER_STATE b);
void yy_init_buffer(YY_BUFFER_STATE b, FILE *file);
void yy_flush_buffer(YY_BUFFER_STATE b);
#define YY_FLUSH_BUFFER yy_flush_buffer(yy_current_buffer)

YY_BUFFER_STATE yy_scan_buffer(char *bbase, yy_size_t size);
YY_BUFFER_STATE yy_scan_string(yyconst char *yy_str);
YY_BUFFER_STATE yy_scan_bytes(yyconst char *bytes, int len);

static void *yy_flex_alloc(yy_size_t);
static void *yy_flex_realloc(void *, yy_size_t);
static void yy_flex_free(void *);

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	    if (!yy_current_buffer) \
		yy_current_buffer = yy_create_buffer(yyin, YY_BUF_SIZE); \
	    yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	    if (!yy_current_buffer) \
		yy_current_buffer = yy_create_buffer(yyin, YY_BUF_SIZE); \
	    yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state(void);
static yy_state_type yy_try_NUL_trans(yy_state_type current_state);
static int yy_get_next_buffer(void);

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 64
#define YY_END_OF_BUFFER 65
static yyconst short int yy_acclist[454] =
    {   0,
        2,    2,   65,   50,   64,    2,   50,   64,    4,   64,
       51,   64,   42,   50,   64,   47,   50,   64,    1,   50,
       64,   49,   50,   64,   50,   64,   43,   50,   64,   44,
       50,   64,   50,   64,   48,   49,   50,   64,   50,   64,
       38,   50,   64,   36,   50,   64,   40,   50,   64,   50,
       64,   48,   49,   50,   64,   48,   49,   50,   64,   48,
       49,   50,   64,   48,   49,   50,   64,   48,   49,   50,
       64,   48,   49,   50,   64,   48,   49,   50,   64,   48,
       49,   50,   64,   48,   49,   50,   64,   48,   49,   50,
       64,   48,   49,   50,   64,   48,   49,   50,   64,   48,

       49,   50,   64,   50,   64,   52,   54,   64,   54,   64,
       53,   64,   64,   63,   64,   60,   64,   62,   64,   64,
       56,   64,   59,   64,   64,   58,   64,   55,   64,   57,
       64,    2,    4,   37,    1,   49,   35,   46,   48,   49,
       45,   39,   41,    3,   48,   49,   48,   49,   48,   49,
       48,   49,   48,   49,   48,   49,   18,   48,   49,   48,
       49,   48,   49,   48,   49,   48,   49,   48,   49,   25,
       48,   49,   48,   49,   48,   49,   48,   49,   48,   49,
       48,   49,   48,   49,   48,   49,   48,   49,   34,   52,
       52,   53,   63,   60,   62,   61,   56,   59,   55,   57,

       48,   49,   48,   49,   48,   49,   48,   49,   48,   49,
       48,   49,   48,   49,   48,   49,   17,   48,   49,   48,
       49,   20,   48,   49,   48,   49,   48,   49,   48,   49,
       48,   49,   48,   49,   48,   49,   48,   49,   48,   49,
       48,   49,   48,   49,   48,   49,    5,   48,   49,   48,
       49,   48,   49,   48,   49,   48,   49,   48,   49,   48,
       49,   48,   49,   48,   49,   48,   49,   16,   48,   49,
       48,   49,   48,   49,   22,   48,   49,   48,   49,   48,
       49,   48,   49,   48,   49,   48,   49,   48,   49,   48,
       49,   48,   49,   48,   49,   48,   49,   48,   49,   48,

       49,   48,   49,   48,   49,   48,   49,   48,   49,   48,
       49,   14,   48,   49,   48,   49,   19,   48,   49,   48,
       49,   48,   49,   48,   49,   48,   49,   48,   49,   28,
       48,   49,   48,   49,   48,   49,   48,   49,   48,   49,
       48,   49,    6,   48,   49,   48,   49,    8,   48,   49,
       48,   49,   48,   49,   48,   49,   48,   49,   48,   49,
       48,   49,   48,   49,   48,   49,   48,   49,   48,   49,
       27,   48,   49,   29,   48,   49,   30,   48,   49,   31,
       48,   49,   48,   49,   48,   49,    7,   48,   49,   48,
       49,   48,   49,   11,   48,   49,   12,   48,   49,   48,

       49,   15,   48,   49,   48,   49,   48,   49,   24,   48,
       49,   48,   49,   48,   49,   33,   48,   49,    9,   48,
       49,   48,   49,   48,   49,   21,   48,   49,   48,   49,
       26,   48,   49,   32,   48,   49,   48,   49,   13,   48,
       49,   48,   49,   48,   49,   23,   48,   49,   48,   49,
       10,   48,   49
    } ;
/* *INDENT-OFF* */
static yyconst short int yy_accept[218] =
    {   0,
        1,    2,    3,    3,    3,    3,    3,    3,    3,    4,
        6,    9,   11,   13,   16,   19,   22,   25,   27,   30,
       33,   35,   39,   41,   44,   47,   50,   52,   56,   60,
       64,   68,   72,   76,   80,   84,   88,   92,   96,  100,
      104,  106,  109,  111,  113,  114,  116,  118,  120,  121,
      123,  125,  126,  128,  130,  132,  133,  134,  135,  136,
      137,  138,  139,  141,  142,  143,  144,  145,  145,  147,
      149,  151,  153,  155,  157,  160,  162,  164,  166,  168,
      170,  173,  175,  177,  179,  181,  183,  185,  187,  189,
      190,  191,  192,  193,  194,  195,  196,  196,  197,  198,

      199,  200,  201,  203,  205,  207,  209,  211,  213,  215,
      217,  220,  222,  225,  227,  229,  231,  233,  235,  237,
      239,  241,  243,  245,  247,  250,  252,  254,  256,  258,
      260,  262,  264,  266,  268,  271,  273,  275,  278,  280,
      282,  284,  286,  288,  290,  292,  294,  296,  298,  300,
      302,  304,  306,  308,  310,  312,  315,  317,  320,  322,
      324,  326,  328,  330,  333,  335,  337,  339,  341,  343,
      346,  348,  351,  353,  355,  357,  359,  361,  363,  365,
      367,  369,  371,  374,  377,  380,  383,  385,  387,  390,
      392,  394,  397,  400,  402,  405,  407,  409,  412,  414,

      416,  419,  422,  424,  426,  429,  431,  434,  437,  439,
      442,  444,  446,  449,  451,  454,  454
    } ;
static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    8,    1,    9,   10,   11,
       12,    1,   13,    1,   14,    1,    1,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   15,    1,   16,
       17,   18,    1,    1,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
        1,   19,    1,    1,   20,    1,   21,   22,   23,   24,

       25,   26,   27,   28,   29,   14,   14,   30,   31,   32,
       33,   34,   14,   35,   36,   37,   38,   39,   14,   40,
       41,   14,    1,   42,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;
static yyconst int yy_meta[43] =
    {   0,
        1,    2,    3,    3,    1,    4,    1,    5,    1,    4,
        1,    1,    1,    6,    1,    1,    1,    1,    4,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    1
    } ;
static yyconst short int yy_base[230] =
    {   0,
        0,    0,   41,   44,   47,   50,   52,   60,  434,  435,
      431,  435,  429,  414,  435,    0,    0,  421,  435,  435,
      412,  420,  410,  409,  435,  408,   69,   49,   53,   51,
       57,   59,   61,   69,   66,   70,   67,   83,   72,   75,
      382,  421,  435,  435,  419,    0,   93,    0,  418,    0,
      435,  417,  435,    0,    0,  417,  435,  435,    0,    0,
      435,  435,  410,  435,  435,  435,  435,  414,   77,   91,
       95,  103,   93,   98,  408,  101,  104,  105,  107,  106,
      404,  110,  111,  113,  123,  114,  115,  117,  124,  435,
      404,    0,  435,    0,  152,    0,  397,  435,    0,  435,

        0,  435,  128,  132,  134,  125,  149,  141,  151,  154,
      388,  155,  387,  135,  140,  156,  160,  164,  163,  167,
      165,  168,  169,  173,  386,  175,  171,  178,  179,  176,
      183,  185,  191,  195,  380,  196,  198,  200,  201,  202,
      204,  203,  210,  211,  213,  214,  217,  216,  218,  219,
      222,  224,  228,  232,  234,  379,  236,  374,  235,  239,
      240,  241,  244,  368,  245,  246,  249,  253,  254,  358,
      255,  336,  256,  258,  261,  267,  262,  269,  270,  272,
      275,  278,  335,  334,  333,  332,  271,  280,  331,  282,
      277,  330,  328,  286,  327,  285,  288,  325,  287,  293,

      324,  323,  289,  302,  322,  292,  321,  320,  298,  317,
      307,  308,  316,  312,  314,  435,  345,  351,  357,  363,
      365,  367,  373,  379,  385,  391,  397,  403,  409
    } ;
static yyconst short int yy_def[230] =
    {   0,
      216,    1,  217,  217,  218,  218,  219,  219,  216,  216,
      216,  216,  216,  216,  216,  220,  221,  216,  216,  216,
      216,  222,  216,  216,  216,  216,  216,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      216,  223,  216,  216,  216,  224,  216,  225,  216,  226,
      216,  216,  216,  227,  228,  216,  216,  216,  220,  221,
      216,  216,  222,  216,  216,  216,  216,  216,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  216,
      223,  229,  216,  224,  216,  225,  216,  216,  226,  216,

      227,  216,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,

      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,    0,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216
    } ;
static yyconst short int yy_nxt[478] =
    {   0,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   15,
       19,   20,   21,   22,   23,   24,   25,   26,   27,   22,
       22,   28,   29,   30,   31,   22,   22,   32,   33,   22,
       34,   22,   35,   36,   37,   38,   39,   22,   40,   22,
       22,   41,   43,   44,   45,   43,   44,   45,   47,   48,
       49,   47,   48,   49,   51,   52,   60,   53,   60,   54,
       60,   53,   51,   52,   60,   53,   60,   54,   60,   53,
       55,   67,   68,   60,   60,   72,   60,   60,   55,   60,
       70,   69,   60,   74,   60,   71,   75,   84,   73,   78,
       60,   76,   77,   79,   95,   96,   97,   81,   60,   82,

       60,   80,   60,   89,   83,   60,   88,   85,   60,  103,
       60,   60,   60,   60,   60,   86,  109,   60,   60,   87,
       60,   60,   60,  104,   60,  105,  106,  110,  107,  116,
       60,   60,   60,  114,  112,   60,  108,  111,  115,   60,
      113,   60,   60,  118,  119,  123,  117,   60,   60,  122,
      128,  121,  120,   95,   96,   97,   60,  125,   60,  124,
      126,   60,   60,   60,  127,  131,  137,   60,  129,  130,
       60,   60,   60,  132,   60,   60,   60,  138,   60,  133,
       60,  134,   60,   60,  136,   60,   60,  135,  140,  142,
       60,  143,   60,  139,  141,  149,  145,  148,   60,  144,

      151,  147,   60,   60,  146,   60,  150,   60,   60,   60,
       60,   60,  155,  153,  154,  152,  156,   60,   60,  157,
       60,   60,  160,   60,   60,   60,   60,  164,  159,   60,
      161,   60,  165,  166,  162,   60,  158,  163,  169,   60,
      170,   60,   60,   60,  167,  172,   60,   60,   60,  171,
      168,   60,   60,   60,  173,  176,   60,  175,  174,  179,
       60,   60,   60,   60,  181,   60,  177,  178,   60,   60,
      185,  180,  182,  187,   60,  186,   60,   60,   60,   60,
      183,  184,   60,  188,   60,   60,  191,   60,  190,   60,
      194,  189,   60,   60,   60,   60,   60,  192,  199,   60,

       60,  196,  193,  197,  201,   60,  195,  200,  204,   60,
      198,  202,  203,  206,   60,   60,  207,  208,  212,   60,
      211,   60,  205,   60,   60,  209,  210,   60,   60,   60,
       60,   60,   60,  213,   60,   60,  215,   60,   60,   60,
       60,   60,   60,   60,  214,   42,   42,   42,   42,   42,
       42,   46,   46,   46,   46,   46,   46,   50,   50,   50,
       50,   50,   50,   59,   59,   60,   59,   59,   59,   60,
       60,   63,   63,   91,   91,   60,   91,   91,   91,   94,
       94,   60,   94,   94,   94,   98,   60,   60,   98,   98,
       98,   99,   99,   60,   60,   60,   99,  101,  101,   96,

      101,  101,  101,  102,  102,   92,  102,  102,  102,   92,
       92,   60,   92,   92,   92,   60,   67,   60,   56,  100,
       96,   93,   92,   90,   66,   65,   64,   60,   62,   61,
       58,   57,   56,  216,    9,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216
    } ;
static yyconst short int yy_chk[478] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    3,    3,    4,    4,    4,    5,    5,
        5,    6,    6,    6,    7,    7,   28,    7,   30,    7,
       29,    7,    8,    8,   31,    8,   32,    8,   33,    8,
        7,   27,   27,   35,   37,   30,   34,   36,    8,   39,
       29,   28,   40,   32,   69,   29,   33,   37,   31,   34,
       38,   33,   33,   34,   47,   47,   47,   35,   70,   35,

       73,   34,   71,   40,   36,   74,   39,   38,   76,   69,
       72,   77,   78,   80,   79,   38,   73,   82,   83,   38,
       84,   86,   87,   70,   88,   71,   71,   74,   72,   80,
       85,   89,  106,   78,   76,  103,   72,   74,   79,  104,
       77,  105,  114,   83,   84,   88,   82,  115,  108,   87,
      106,   86,   85,   95,   95,   95,  107,  103,  109,   89,
      104,  110,  112,  116,  105,  108,  114,  117,  107,  107,
      119,  118,  121,  109,  120,  122,  123,  115,  127,  109,
      124,  109,  126,  130,  112,  128,  129,  110,  117,  119,
      131,  120,  132,  116,  118,  127,  122,  126,  133,  121,

      129,  124,  134,  136,  123,  137,  128,  138,  139,  140,
      142,  141,  132,  130,  131,  129,  133,  143,  144,  134,
      145,  146,  138,  148,  147,  149,  150,  142,  137,  151,
      139,  152,  143,  144,  140,  153,  136,  141,  147,  154,
      148,  155,  159,  157,  145,  150,  160,  161,  162,  149,
      146,  163,  165,  166,  151,  154,  167,  153,  152,  159,
      168,  169,  171,  173,  161,  174,  155,  157,  175,  177,
      166,  160,  162,  168,  176,  167,  178,  179,  187,  180,
      163,  165,  181,  169,  191,  182,  174,  188,  173,  190,
      177,  171,  196,  194,  199,  197,  203,  175,  182,  206,

      200,  179,  176,  180,  188,  209,  178,  187,  194,  204,
      181,  190,  191,  197,  211,  212,  199,  200,  209,  214,
      206,  215,  196,  213,  210,  203,  204,  208,  207,  205,
      202,  201,  198,  211,  195,  193,  214,  192,  189,  186,
      185,  184,  183,  172,  212,  217,  217,  217,  217,  217,
      217,  218,  218,  218,  218,  218,  218,  219,  219,  219,
      219,  219,  219,  220,  220,  170,  220,  220,  220,  221,
      221,  222,  222,  223,  223,  164,  223,  223,  223,  224,
      224,  158,  224,  224,  224,  225,  156,  135,  225,  225,
      225,  226,  226,  125,  113,  111,  226,  227,  227,   97,

      227,  227,  227,  228,  228,   91,  228,  228,  228,  229,
      229,   81,  229,  229,  229,   75,   68,   63,   56,   52,
       49,   45,   42,   41,   26,   24,   23,   22,   21,   18,
       14,   13,   11,    9,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216
    } ;
/* *INDENT-ON* */
static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#define INITIAL 0
/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (C) 2002 Roman Zippel <zippel@linux-m68k.org>
 */
#define YY_NEVER_INTERACTIVE 1
#define ASSIGN_VAL 1
#define HELP 2
#define STRING 3


#include <assert.h>
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "lkc.h"
#include "parser.tab.h"

#define YY_DECL		static int yylex1(void)

#define START_STRSIZE	16

#ifdef _WIN32
#define YY_NO_UNISTD_H
#define YY_INPUT(buf,result,max_size) \
	result = fread(buf, 1, max_size, yyin); \
	if (!result) \
	{ \
		if (ferror(yyin)) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = YY_NULL; \
}
#ifndef PATH_MAX
#define PATH_MAX _MAX_PATH /* <stdlib.h> */
#endif
#endif

static struct {
	struct file *file;
	int lineno;
} current_pos;

static int prev_prev_token = T_EOL;
static int prev_token = T_EOL;
static char *text;
static int text_size, text_asize;

struct buffer {
	struct buffer *parent;
	YY_BUFFER_STATE state;
};

static struct buffer *current_buf;

static int last_ts, first_ts;

int yylex_destroy(void);

void zconf_free(void)
{
	yylex_destroy();
	memset(&current_pos, 0, sizeof(current_pos));
	prev_prev_token = T_EOL; prev_token = T_EOL;
	text = NULL; text_size = 0; text_asize = 0;
	current_buf = NULL;
        last_ts = 0; first_ts = 0;
}

static char *expand_token(const char *in, size_t n);
static void append_expanded_string(const char *in);
static void zconf_endhelp(void);
static void zconf_endfile(void);

static void new_string(void)
{
	text = xmalloc(START_STRSIZE);
	text_asize = START_STRSIZE;
	text_size = 0;
	*text = 0;
}

static void append_string(const char *str, int size)
{
	int new_size = text_size + size + 1;
	if (new_size > text_asize) {
		new_size += START_STRSIZE - 1;
		new_size &= -START_STRSIZE;
		text = xrealloc(text, new_size);
		text_asize = new_size;
	}
	memcpy(text + text_size, str, size);
	text_size += size;
	text[text_size] = 0;
}

static void alloc_string(const char *str, int size)
{
	text = xmalloc(size + 1);
	memcpy(text, str, size);
	text[size] = 0;
}

static void warn_ignored_character(char chr)
{
	fprintf(stderr,
	        "%s:%d: warning: ignoring unsupported character '%c'\n",
	        current_file->name, yylineno, chr);
}

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_NO_UNISTD_H
/*
 * Non-POSIX systems may lack unistd.h, or provide a useless stub.
 * Let the user decide how to deal with it.
 */
#include <unistd.h>
#endif

static int yy_init_globals (void);
int yylex_destroy(void);

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap();
#else
extern int yywrap(void);
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput(int c, char *buf_ptr);
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy(char *, yyconst char *, int);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen(yyconst char *);
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput();
#else
static int input(void);
#endif
#endif

#ifndef YY_STACK_USED
#define YY_STACK_USED 0
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state(int new_state);
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state(void);
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state(void);
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* workaround for defective implementation of gcc attribute warn_unused_result */
#if defined(__GNUC__) && defined(_FORTIFY_SOURCE)
#define YY_IGNORE_RC(func) do { if (func != 0) {} } while(0)
#else
#define YY_IGNORE_RC(func) (void) func
#endif /* gcc workaround */

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO YY_IGNORE_RC(fwrite(yytext, (size_t) yyleng, (size_t) 1, yyout))
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if (yy_current_buffer->yy_is_interactive) \
	    { \
		int c = '*', n; \
		for (n = 0; n < (int) max_size && \
		     (c = getc(yyin)) != EOF && c != '\n'; ++n) \
		    buf[n] = (char) c; \
		if (c == '\n') \
		    buf[n++] = (char) c; \
		if (c == EOF && ferror(yyin)) \
		    YY_FATAL_ERROR("input in flex scanner failed"); \
		result = n; \
	    } \
	else \
	    { \
		size_t readresult; \
		if (((readresult = fread(buf, (size_t) 1, (size_t) max_size, yyin)) == 0) \
		      && ferror(yyin)) \
		{ \
		    YY_FATAL_ERROR("input in flex scanner failed"); \
		} \
		result = (int) readresult; \
	    }
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
/* if the macro is defined, this function is unused */
static void
yy_fatal_error(yyconst char msg[])
{
    (void) fprintf(stderr, "%s\n", msg);
    exit(YY_EXIT_FAILURE);
}
#define YY_FATAL_ERROR(msg) yy_fatal_error(msg)
#endif


/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex (void)
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
{
    yy_state_type yy_current_state;
    char *yy_cp, *yy_bp;
    int yy_act;


	int str = 0;
	int ts, i;


    if (yy_init) {
	yy_init = 0;

#ifdef YY_USER_INIT
	YY_USER_INIT;
#endif

	if (!yy_start)
	    yy_start = 1;	/* first start state */

	if (!yyin)
	    yyin = stdin;

	if (!yyout)
	    yyout = stdout;

	if (!yy_current_buffer)
	    yy_current_buffer =
		yy_create_buffer(yyin, YY_BUF_SIZE);

	yy_load_buffer_state();
    }

    while (1) {
	/* loops until end-of-file is reached */
	yy_cp = yy_c_buf_p;

	/* Support of yytext. */
	*yy_cp = yy_hold_char;

	/* yy_bp points to the position in yy_ch_buf of the start of
	 * the current run.
	 */
	yy_bp = yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;
	yy_match:
	do {
	    YY_CHAR yy_c = (YY_CHAR) yy_ec[YY_SC_TO_UI(*yy_cp)];
	    while (yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state) {
		yy_current_state = (int) yy_def[yy_current_state];
		if (yy_current_state >= 217)
		    yy_c = (YY_CHAR) yy_meta[(unsigned int) yy_c];
	    }
	    yy_current_state = (yy_state_type) yy_nxt[yy_base[yy_current_state] + yy_c];
	    *yy_state_ptr++ = yy_current_state;
	    ++yy_cp;
	}
	while (yy_base[yy_current_state] != 435);

	yy_find_action:
	yy_current_state = *--yy_state_ptr;
	yy_lp = yy_accept[yy_current_state];
	find_rule: /* we branch to this label when backing up */
	for ( ; ; ) {
	    /* until we find what rule we matched */
	    if (yy_lp && yy_lp < yy_accept[yy_current_state + 1]) {
		yy_act = (int) yy_acclist[yy_lp];
		    {
		    yy_full_match = yy_cp;
		    break;
		}
	    }
	    --yy_cp;
	    yy_current_state = *--yy_state_ptr;
	    yy_lp = yy_accept[yy_current_state];
	}

	YY_DO_BEFORE_ACTION;

	if (yy_act != YY_END_OF_BUFFER) {
	    int yyl;
	    for (yyl = 0; yyl < yyleng; ++yyl)
		if (yytext[yyl] == '\n')
		    ++yylineno;
	}

	do_action:	/* This label is used only to access EOF actions. */

	switch (yy_act) {
	    /* beginning of action switch */
		case 1:
	    YY_RULE_SETUP
	    /* ignore comment */
	    YY_BREAK
	case 2:
	    YY_RULE_SETUP
	    /* whitespaces */
	    YY_BREAK
	case 3:
	    YY_RULE_SETUP
	    /* escaped new line */
	    YY_BREAK
	case 4:
	    YY_RULE_SETUP
	    return T_EOL;
	    YY_BREAK
	case 5:
	    YY_RULE_SETUP
	    return T_BOOL;
	    YY_BREAK
	case 6:
	    YY_RULE_SETUP
	    return T_CHOICE;
	    YY_BREAK
	case 7:
	    YY_RULE_SETUP
	    return T_COMMENT;
	    YY_BREAK
	case 8:
	    YY_RULE_SETUP
	    return T_CONFIG;
	    YY_BREAK
	case 9:
	    YY_RULE_SETUP
	    return T_DEF_BOOL;
	    YY_BREAK
	case 10:
	    YY_RULE_SETUP
	    return T_DEF_TRISTATE;
	    YY_BREAK
	case 11:
	    YY_RULE_SETUP
	    return T_DEFAULT;
	    YY_BREAK
	case 12:
	    YY_RULE_SETUP
	    return T_DEPENDS;
	    YY_BREAK
	case 13:
	    YY_RULE_SETUP
	    return T_ENDCHOICE;
	    YY_BREAK
	case 14:
	    YY_RULE_SETUP
	    return T_ENDIF;
	    YY_BREAK
	case 15:
	    YY_RULE_SETUP
	    return T_ENDMENU;
	    YY_BREAK
	case 16:
	    YY_RULE_SETUP
	    return T_HELP;
	    YY_BREAK
	case 17:
	    YY_RULE_SETUP
	    return T_HEX;
	    YY_BREAK
	case 18:
	    YY_RULE_SETUP
	    return T_IF;
	    YY_BREAK
	case 19:
	    YY_RULE_SETUP
	    return T_IMPLY;
	    YY_BREAK
	case 20:
	    YY_RULE_SETUP
	    return T_INT;
	    YY_BREAK
	case 21:
	    YY_RULE_SETUP
	    return T_MAINMENU;
	    YY_BREAK
	case 22:
	    YY_RULE_SETUP
	    return T_MENU;
	    YY_BREAK
	case 23:
	    YY_RULE_SETUP
	    return T_MENUCONFIG;
	    YY_BREAK
	case 24:
	    YY_RULE_SETUP
	    return T_MODULES;
	    YY_BREAK
	case 25:
	    YY_RULE_SETUP
	    return T_ON;
	    YY_BREAK
	case 26:
	    YY_RULE_SETUP
	    return T_OPTIONAL;
	    YY_BREAK
	case 27:
	    YY_RULE_SETUP
	    return T_PROMPT;
	    YY_BREAK
	case 28:
	    YY_RULE_SETUP
	    return T_RANGE;
	    YY_BREAK
	case 29:
	    YY_RULE_SETUP
	    return T_SELECT;
	    YY_BREAK
	case 30:
	    YY_RULE_SETUP
	    return T_SOURCE;
	    YY_BREAK
	case 31:
	    YY_RULE_SETUP
	    return T_STRING;
	    YY_BREAK
	case 32:
	    YY_RULE_SETUP
	    return T_TRISTATE;
	    YY_BREAK
	case 33:
	    YY_RULE_SETUP
	    return T_VISIBLE;
	    YY_BREAK
	case 34:
	    YY_RULE_SETUP
	    return T_OR;
	    YY_BREAK
	case 35:
	    YY_RULE_SETUP
	    return T_AND;
	    YY_BREAK
	case 36:
	    YY_RULE_SETUP
	    return T_EQUAL;
	    YY_BREAK
	case 37:
	    YY_RULE_SETUP
	    return T_UNEQUAL;
	    YY_BREAK
	case 38:
	    YY_RULE_SETUP
	    return T_LESS;
	    YY_BREAK
	case 39:
	    YY_RULE_SETUP
	    return T_LESS_EQUAL;
	    YY_BREAK
	case 40:
	    YY_RULE_SETUP
	    return T_GREATER;
	    YY_BREAK
	case 41:
	    YY_RULE_SETUP
	    return T_GREATER_EQUAL;
	    YY_BREAK
	case 42:
	    YY_RULE_SETUP
	    return T_NOT;
	    YY_BREAK
	case 43:
	    YY_RULE_SETUP
	    return T_OPEN_PAREN;
	    YY_BREAK
	case 44:
	    YY_RULE_SETUP
	    return T_CLOSE_PAREN;
	    YY_BREAK
	case 45:
	    YY_RULE_SETUP
	    return T_COLON_EQUAL;
	    YY_BREAK
	case 46:
	    YY_RULE_SETUP
	    return T_PLUS_EQUAL;
	    YY_BREAK
	case 47:
	    YY_RULE_SETUP
	    {
		str = yytext[0];
		new_string();
		BEGIN(STRING);
	    }
	    YY_BREAK
	case 48:
	    YY_RULE_SETUP
	    {
		alloc_string(yytext, yyleng);
		yylval.string = text;
		return T_WORD;
	    }
	    YY_BREAK
	case 49:
	    YY_RULE_SETUP
	    {
		/* this token includes at least one '$' */
		yylval.string = expand_token(yytext, yyleng);
		if (strlen(yylval.string))
		return T_WORD;
		free(yylval.string);
	    }
	    YY_BREAK
	case 50:
	    YY_RULE_SETUP
	    warn_ignored_character(*yytext);
	    YY_BREAK
	case 51:
	    YY_RULE_SETUP
	    warn_ignored_character(*yytext);
	    YY_BREAK

	case 52:
	    YY_RULE_SETUP
	    {
		alloc_string(yytext, yyleng);
		yylval.string = text;
		return T_ASSIGN_VAL;
	    }
	    YY_BREAK
	case 53:
	    YY_RULE_SETUP
	    { BEGIN(INITIAL); return T_EOL; }
	    YY_BREAK
	case 54:
	    YY_RULE_SETUP

	    YY_BREAK


	case 55:
	    YY_RULE_SETUP
	    append_expanded_string(yytext);
	    YY_BREAK
	case 56:
	    YY_RULE_SETUP
	    {
		append_string(yytext, yyleng);
	    }
	    YY_BREAK
	case 57:
	    YY_RULE_SETUP
	    {
		append_string(yytext + 1, yyleng - 1);
	    }
	    YY_BREAK
	case 58:
	    YY_RULE_SETUP
	    {
		if (str == yytext[0]) {
		    BEGIN(INITIAL);
		    yylval.string = text;
		    return T_WORD_QUOTE;
		} else
		append_string(yytext, 1);
	    }
	    YY_BREAK
	case 59:
	    YY_RULE_SETUP
	    {
		fprintf(stderr,
"%s:%d: warning: multi-line strings not supported\n"		,
		zconf_curname(), zconf_lineno());
		unput('\n');
		BEGIN(INITIAL);
		yylval.string = text;
		return T_WORD_QUOTE;
	    }
	    YY_BREAK
	case YY_STATE_EOF(STRING):
	    {
		BEGIN(INITIAL);
		yylval.string = text;
		return T_WORD_QUOTE;
	    }
	    YY_BREAK


	case 60:
	    YY_RULE_SETUP
	    {
		ts = 0;
		for (i = 0; i < yyleng; i++) {
		    if (yytext[i] == '\t')
		    ts = (ts & ~7) + 8;
		    else
		    ts++;
		}
		last_ts = ts;
		if (first_ts) {
		    if (ts < first_ts) {
			zconf_endhelp();
			return T_HELPTEXT;
		    }
		    ts -= first_ts;
		    while (ts > 8) {
			append_string("        ", 8);
			ts -= 8;
		    }
		    append_string("        ", ts);
		}
	    }
	    YY_BREAK
	case 61:
	    *yy_cp = yy_hold_char;	/* undo effects of setting up yytext */
	    yy_c_buf_p = yy_cp -= 1;
	    YY_DO_BEFORE_ACTION;	/* set up yytext again */
	    YY_RULE_SETUP
	    {
		zconf_endhelp();
		return T_HELPTEXT;
	    }
	    YY_BREAK
	case 62:
	    YY_RULE_SETUP
	    {
		append_string("\n", 1);
	    }
	    YY_BREAK
	case 63:
	    YY_RULE_SETUP
	    {
		while (yyleng) {
		    if ((yytext[yyleng-1] != ' ') && (yytext[yyleng-1] != '\t'))
		    break;
		    yyleng--;
		}
		append_string(yytext, yyleng);
		if (!first_ts)
		first_ts = last_ts;
	    }
	    YY_BREAK
	case YY_STATE_EOF(HELP):
	    {
		zconf_endhelp();
		return T_HELPTEXT;
	    }
	    YY_BREAK

	case YY_STATE_EOF(INITIAL):
	case YY_STATE_EOF(ASSIGN_VAL):
	    {
		BEGIN(INITIAL);

		if (prev_token != T_EOL && prev_token != T_HELPTEXT) {
		    fprintf(stderr, "%s:%d: warning: no new line at end of file\n",
		    current_file->name, yylineno);
		    return T_EOL;
		}

		if (current_file) {
		    zconf_endfile();
		    return T_EOL;
		}
		fclose(yyin);
		yyterminate();
	    }
	    YY_BREAK
	case 64:
	    YY_RULE_SETUP
	ECHO;
	    YY_BREAK

	    case YY_END_OF_BUFFER:
		{
		    /* Amount of text matched not including the EOB char. */
		    int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		    /* Undo the effects of YY_DO_BEFORE_ACTION. */
		    *yy_cp = yy_hold_char;
		    YY_RESTORE_YY_MORE_OFFSET

		    if (yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW) {
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
		    }

		    /* Note that here we test for yy_c_buf_p "<=" to the position
		     * of the first EOB in the buffer, since yy_c_buf_p will
		     * already have been incremented past the NUL character
		     * (since all states make transitions on EOB to the
		     * end-of-buffer state).  Contrast this with the test
		     * in input().
		     */
		    if (yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars]) {
			/* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans(yy_current_state);

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if (yy_next_state) {
			    /* Consume the NUL. */
			    yy_cp = ++yy_c_buf_p;
			    yy_current_state = yy_next_state;
			    goto yy_match;
			} else {
			yy_cp = yy_c_buf_p;
			goto yy_find_action;
		    }
		} else {
		    switch (yy_get_next_buffer()) {
		    case EOB_ACT_END_OF_FILE:
			{
			    yy_did_buffer_switch_on_eof = 0;

			    if (yywrap()) {
				/* Note: because we've taken care in
				 * yy_get_next_buffer() to have set up
				 * yytext, we can now set up
				 * yy_c_buf_p so that if some total
				 * hoser (like flex itself) wants to
				 * call the scanner after we return the
				 * YY_NULL, it'll still work - another
				 * YY_NULL will get returned.
				 */
				yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

				yy_act = YY_STATE_EOF(YY_START);
				goto do_action;
			    } else {
				if (!yy_did_buffer_switch_on_eof)
				    YY_NEW_FILE;
			    }
			    break;
			}

		    case EOB_ACT_CONTINUE_SCAN:
			yy_c_buf_p =
			    yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			yy_cp = yy_c_buf_p;
			yy_bp = yytext_ptr + YY_MORE_ADJ;
			goto yy_match;

		    case EOB_ACT_LAST_MATCH:
			yy_c_buf_p =
			    &yy_current_buffer->yy_ch_buf[yy_n_chars];

			yy_current_state = yy_get_previous_state();

			yy_cp = yy_c_buf_p;
			yy_bp = yytext_ptr + YY_MORE_ADJ;
			goto yy_find_action;
		    }
		}
		break;
	    }

	default:
	    YY_FATAL_ERROR("fatal flex scanner internal error--no action found");
	}			/* end of action switch */
    }				/* end of scanning one token */
}				/* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int
yy_get_next_buffer(void)
{
    char *dest = yy_current_buffer->yy_ch_buf;
    char *source = yytext_ptr;
    int number_to_move, i;
    int ret_val;

    if (yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1])
	YY_FATAL_ERROR("fatal flex scanner internal error--end of buffer missed");

    if (yy_current_buffer->yy_fill_buffer == 0) {
	/* Don't try to fill the buffer, so this is an EOF. */
	if (yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1) {
	    /* We matched a single character, the EOB, so
	     * treat this as a final EOF.
	     */
	    return EOB_ACT_END_OF_FILE;
	} else {
	    /* We matched some text prior to the EOB, first
	     * process it.
	     */
	    return EOB_ACT_LAST_MATCH;
	}
    }

    /* Try to read more data. */

    /* First move last chars to start of buffer. */
    number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

    for (i = 0; i < number_to_move; ++i)
	*(dest++) = *(source++);

    if (yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING)
	/* don't do the read, it's not guaranteed to return an EOF,
	 * just force an EOF
	 */
	yy_current_buffer->yy_n_chars = yy_n_chars = 0;

    else {
	int num_to_read = (int) ((long) yy_current_buffer->yy_buf_size - (long) number_to_move - 1);

	while (num_to_read <= 0) {
	    /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
	    YY_FATAL_ERROR("input buffer overflow, can't enlarge buffer because scanner uses REJECT");
#else

	    /* just a shorter name for the current buffer */
	    YY_BUFFER_STATE b = yy_current_buffer;

	    int yy_c_buf_p_offset = (int) (yy_c_buf_p - b->yy_ch_buf);

	    if (b->yy_is_our_buffer) {
		int new_size = (int) (b->yy_buf_size * 2);

		if (new_size <= 0)
		    b->yy_buf_size += b->yy_buf_size / 8;
		else
		    b->yy_buf_size *= 2;

		b->yy_ch_buf = (char *)
		/* Include room in for 2 EOB chars. */
		    yy_flex_realloc((void *) b->yy_ch_buf,
				    b->yy_buf_size + 2);
	    } else
		/* Can't grow it, we don't own it. */
		b->yy_ch_buf = 0;

	    if (!b->yy_ch_buf)
		YY_FATAL_ERROR("fatal error - scanner input buffer overflow");

	    yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

	    num_to_read = (int) ((long) yy_current_buffer->yy_buf_size - (long) number_to_move - 1);
#endif
	}

	if (num_to_read > YY_READ_BUF_SIZE)
	    num_to_read = YY_READ_BUF_SIZE;

	/* Read in more data. */
	YY_INPUT((&yy_current_buffer->yy_ch_buf[number_to_move]),
		 yy_n_chars, num_to_read);

	yy_current_buffer->yy_n_chars = yy_n_chars;
    }

    if (yy_n_chars == 0) {
	if (number_to_move == YY_MORE_ADJ) {
	    ret_val = EOB_ACT_END_OF_FILE;
	    yyrestart(yyin);
	} else {
	    ret_val = EOB_ACT_LAST_MATCH;
	    yy_current_buffer->yy_buffer_status =
		YY_BUFFER_EOF_PENDING;
	}
    } else
	ret_val = EOB_ACT_CONTINUE_SCAN;

    yy_n_chars += number_to_move;
    yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
    yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

    yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

    return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type
yy_get_previous_state(void)
{
    yy_state_type yy_current_state;
    char *yy_cp;

    yy_current_state = yy_start;
    yy_state_ptr = yy_state_buf;
    *yy_state_ptr++ = yy_current_state;

    for (yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp) {
	YY_CHAR yy_c = (YY_CHAR) (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
	while (yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state) {
	    yy_current_state = (int) yy_def[yy_current_state];
	    if (yy_current_state >= 217)
		yy_c = (YY_CHAR) yy_meta[(unsigned int) yy_c];
	}
	yy_current_state = (yy_state_type) yy_nxt[yy_base[yy_current_state] + yy_c];
	*yy_state_ptr++ = yy_current_state;
    }

    return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans(current_state);
 */

static yy_state_type
yy_try_NUL_trans(yy_state_type yy_current_state)
{
    int yy_is_jam;

    YY_CHAR yy_c = (YY_CHAR) 1;
    while (yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state) {
	yy_current_state = (int) yy_def[yy_current_state];
	if (yy_current_state >= 217)
	    yy_c = (YY_CHAR) yy_meta[(unsigned int) yy_c];
    }
    yy_current_state = (yy_state_type) yy_nxt[yy_base[yy_current_state] + yy_c];
    yy_is_jam = (yy_current_state == 216);
    if (! yy_is_jam)
	*yy_state_ptr++ = yy_current_state;

    return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT
static void
yyunput(int c, char *yy_bp)
{
    char *yy_cp = yy_c_buf_p;

    /* undo effects of setting up yytext */
    *yy_cp = yy_hold_char;

    if (yy_cp < yy_current_buffer->yy_ch_buf + 2) {
	/* need to shift things up to make room */
	/* +2 for EOB chars. */
	int number_to_move = yy_n_chars + 2;
	char *dest = &(yy_current_buffer->yy_ch_buf
				[yy_current_buffer->yy_buf_size + 2]);
	char *source = &yy_current_buffer->yy_ch_buf[number_to_move];

	while (source > yy_current_buffer->yy_ch_buf)
	    *--dest = *--source;

	yy_cp += (int) (dest - source);
	yy_bp += (int) (dest - source);
	yy_current_buffer->yy_n_chars =
	    yy_n_chars = (int) yy_current_buffer->yy_buf_size;

	if (yy_cp < yy_current_buffer->yy_ch_buf + 2)
	    YY_FATAL_ERROR("flex scanner push-back overflow");
    }

    *--yy_cp = (char) c;
    if (c == '\n')
	--yylineno;

    yytext_ptr = yy_bp;
    yy_hold_char = *yy_cp;
    yy_c_buf_p = yy_cp;
}
#endif /* ifndef YY_NO_UNPUT */

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int
yyinput()
#else
static int
input(void)
#endif
{
    int c;

    *yy_c_buf_p = yy_hold_char;

    if (*yy_c_buf_p == YY_END_OF_BUFFER_CHAR) {
	/* yy_c_buf_p now points to the character we want to return.
	 * If this occurs *before* the EOB characters, then it's a
	 * valid NUL; if not, then we've hit the end of the buffer.
	 */
	if (yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars])
	    /* This was really a NUL. */
	    *yy_c_buf_p = '\0';

	else {			/* need more input */
	    int offset = (int) (yy_c_buf_p - yytext_ptr);
	    ++yy_c_buf_p;

	    switch (yy_get_next_buffer()) {
	    case EOB_ACT_LAST_MATCH:
		/* This happens because yy_g_n_b()
		 * sees that we've accumulated a
		 * token and flags that we need to
		 * try matching the token before
		 * proceeding.  But for input(),
		 * there's no matching to consider.
		 * So convert the EOB_ACT_LAST_MATCH
		 * to EOB_ACT_END_OF_FILE.
		 */

		/* Reset buffer status. */
		yyrestart(yyin);

		/* fall through */

	    case EOB_ACT_END_OF_FILE:
		{
		    if (yywrap())
			return EOF;

		    if (!yy_did_buffer_switch_on_eof)
			YY_NEW_FILE;
#ifdef __cplusplus
		    return yyinput();
#else
		    return input();
#endif
		}

	    case EOB_ACT_CONTINUE_SCAN:
		yy_c_buf_p = yytext_ptr + offset;
		break;
	    }
	}
    }

    c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
    *yy_c_buf_p = '\0';		/* preserve yytext */
    yy_hold_char = *++yy_c_buf_p;

    if (c == '\n')
	++yylineno;

    return c;
}
#endif /* ifndef YY_NO_INPUT */

void
yyrestart(FILE *input_file)
{
    if (!yy_current_buffer)
	yy_current_buffer = yy_create_buffer(yyin, YY_BUF_SIZE);

    yy_init_buffer(yy_current_buffer, input_file);
    yy_load_buffer_state();
}

void
yy_switch_to_buffer(YY_BUFFER_STATE new_buffer)
{
    if (yy_current_buffer == new_buffer)
	return;

    if (yy_current_buffer) {
	/* Flush out information for old buffer. */
	*yy_c_buf_p = yy_hold_char;
	yy_current_buffer->yy_buf_pos = yy_c_buf_p;
	yy_current_buffer->yy_n_chars = yy_n_chars;
    }

    yy_current_buffer = new_buffer;
    yy_load_buffer_state();

    /* We don't actually know whether we did this switch during
     * EOF (yywrap()) processing, but the only time this flag
     * is looked at is after yywrap() is called, so it's safe
     * to go ahead and always set it.
     */
    yy_did_buffer_switch_on_eof = 1;
}

void
yy_load_buffer_state(void)
{
    yy_n_chars = yy_current_buffer->yy_n_chars;
    yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
    yyin = yy_current_buffer->yy_input_file;
    yy_hold_char = *yy_c_buf_p;
}

YY_BUFFER_STATE
yy_create_buffer(FILE *file, int size)
{
    YY_BUFFER_STATE b;

    b = (YY_BUFFER_STATE) yy_flex_alloc(sizeof(struct yy_buffer_state));
    if (!b)
	YY_FATAL_ERROR("out of dynamic memory in yy_create_buffer()");

    b->yy_buf_size = (yy_size_t) size;

    /* yy_ch_buf has to be 2 characters longer than the size given because
     * we need to put in 2 end-of-buffer characters.
     */
    b->yy_ch_buf = (char *) yy_flex_alloc(b->yy_buf_size + 2);
    if (!b->yy_ch_buf)
	YY_FATAL_ERROR("out of dynamic memory in yy_create_buffer()");

    b->yy_is_our_buffer = 1;

    yy_init_buffer(b, file);

    return b;
}

void
yy_delete_buffer(YY_BUFFER_STATE b)
{
    if (!b)
	return;

    if (b == yy_current_buffer)
	yy_current_buffer = (YY_BUFFER_STATE) 0;

    if (b->yy_is_our_buffer)
	yy_flex_free((void *) b->yy_ch_buf);

    yy_flex_free((void *) b);
}

void
yy_init_buffer(YY_BUFFER_STATE b, FILE *file)
{
    yy_flush_buffer(b);

    b->yy_input_file = file;
    b->yy_fill_buffer = 1;

#ifndef YY_ALWAYS_INTERACTIVE
#define YY_ALWAYS_INTERACTIVE 0
#endif
#if YY_ALWAYS_INTERACTIVE
    b->yy_is_interactive = 1;
#else
#ifndef YY_NEVER_INTERACTIVE
#define YY_NEVER_INTERACTIVE 0
#endif
#if YY_NEVER_INTERACTIVE
    b->yy_is_interactive = 0;
#else
    b->yy_is_interactive = file ? (isatty(fileno(file)) > 0) : 0;
#endif
#endif
}

void
yy_flush_buffer(YY_BUFFER_STATE b)
{
    if (!b)
	return;

    b->yy_n_chars = 0;

    /* We always need two end-of-buffer characters.  The first causes
     * a transition to the end-of-buffer state.  The second causes
     * a jam in that state.
     */
    b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
    b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

    b->yy_buf_pos = &b->yy_ch_buf[0];

    b->yy_at_bol = 1;
    b->yy_buffer_status = YY_BUFFER_NEW;

    if (b == yy_current_buffer)
	yy_load_buffer_state();
}

#ifndef YY_NO_SCAN_BUFFER
YY_BUFFER_STATE
yy_scan_buffer(char *bbase, yy_size_t size)
{
    YY_BUFFER_STATE b;

    if (size < 2 ||
	bbase[size - 2] != YY_END_OF_BUFFER_CHAR ||
	bbase[size - 1] != YY_END_OF_BUFFER_CHAR)
	/* They forgot to leave room for the EOB's. */
	return 0;

    b = (YY_BUFFER_STATE) yy_flex_alloc(sizeof(struct yy_buffer_state));
    if (!b)
	YY_FATAL_ERROR("out of dynamic memory in yy_scan_buffer()");

    b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
    b->yy_buf_pos = b->yy_ch_buf = bbase;
    b->yy_is_our_buffer = 0;
    b->yy_input_file = 0;
    b->yy_n_chars = (int) b->yy_buf_size;
    b->yy_is_interactive = 0;
    b->yy_at_bol = 1;
    b->yy_fill_buffer = 0;
    b->yy_buffer_status = YY_BUFFER_NEW;

    yy_switch_to_buffer(b);

    return b;
}
#endif

#ifndef YY_NO_SCAN_STRING
YY_BUFFER_STATE
yy_scan_string(yyconst char *yy_str)
{
    int len;
    for (len = 0; yy_str[len]; ++len) {
	;
    }

    return yy_scan_bytes(yy_str, len);
}
#endif

#ifndef YY_NO_SCAN_BYTES
YY_BUFFER_STATE
yy_scan_bytes(yyconst char *bytes, int len)
{
    YY_BUFFER_STATE b;
    char *buf;
    yy_size_t n;
    int i;

    /* Get memory for full buffer, including space for trailing EOB's. */
    n = (yy_size_t) (len + 2);
    buf = (char *) yy_flex_alloc(n);
    if (!buf)
	YY_FATAL_ERROR("out of dynamic memory in yy_scan_bytes()");

    for (i = 0; i < len; ++i)
	buf[i] = bytes[i];

    buf[len] = buf[len + 1] = YY_END_OF_BUFFER_CHAR;

    b = yy_scan_buffer(buf, n);
    if (!b)
	YY_FATAL_ERROR("bad buffer in yy_scan_bytes()");

    /* It's okay to grow etc. this buffer, and we should throw it
     * away when we're done.
     */
    b->yy_is_our_buffer = 1;

    return b;
}
#endif

#ifndef YY_NO_PUSH_STATE
static void
yy_push_state(int new_state)
{
    if (yy_start_stack_ptr >= yy_start_stack_depth) {
	yy_size_t new_size;

	yy_start_stack_depth += YY_START_STACK_INCR;
	new_size = (yy_size_t) yy_start_stack_depth * sizeof(int);

	if (!yy_start_stack)
	    yy_start_stack = (int *) yy_flex_alloc(new_size);

	else
	    yy_start_stack = (int *) yy_flex_realloc((void *) yy_start_stack,
						     new_size);

	if (!yy_start_stack)
	    YY_FATAL_ERROR("out of memory expanding start-condition stack");
    }

    yy_start_stack[yy_start_stack_ptr++] = YY_START;

    BEGIN(new_state);
}
#endif

#ifndef YY_NO_POP_STATE
static void
yy_pop_state(void)
{
    if (--yy_start_stack_ptr < 0)
	YY_FATAL_ERROR("start-condition stack underflow");

    BEGIN(yy_start_stack[yy_start_stack_ptr]);
}
#endif

#ifndef YY_NO_TOP_STATE
static int
yy_top_state(void)
{
    return yy_start_stack[yy_start_stack_ptr - 1];
}
#endif

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
	    { \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
	    } \
	while (0)

static int yy_init_globals(void)
{
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    yylineno = 1;

    yy_current_buffer = 0;
    yy_c_buf_p = (char *) 0;
    yy_init = 1;
    yy_start = 0;

    yyin = (FILE *) 0;
    yyout = (FILE *) 0;

    return 0;
}

int yylex_destroy(void)
{
    if (YY_CURRENT_BUFFER) {
	yy_delete_buffer(YY_CURRENT_BUFFER);
	YY_CURRENT_BUFFER = NULL;
    }

    /* Reset the globals. This is important in a non-reentrant scanner so
     * the next time yylex() is called, initialization will occur. */
    yy_init_globals();

    return 0;
}

/* Internal utility routines. */

#ifndef yytext_ptr
static void
yy_flex_strncpy(char *s1, yyconst char *s2, int n)
{
    int i;
    for (i = 0; i < n; ++i)
	s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int
yy_flex_strlen(yyconst char *s)
{
    int n;
    for (n = 0; s[n]; ++n) {
	;
    }

    return n;
}
#endif

static void *
yy_flex_alloc(yy_size_t size)
{
    return (void *) malloc(size);
}

static void *
yy_flex_realloc(void *ptr, yy_size_t size)
{
    /* The cast to (char *) in the following accommodates both
     * implementations that use char* generic pointers, and those
     * that use void* generic pointers.  It works with the latter
     * because both ANSI C and C++ allow castless assignment from
     * any pointer type to void*, and deal with argument conversions
     * as though doing an assignment.
     */
    return (void *) realloc((char *) ptr, size);
}

static void
yy_flex_free(void *ptr)
{
    free(ptr);
}

#ifndef YY_MAIN
#define YY_MAIN 0
#endif
#if YY_MAIN
int
main(void)
{
    yylex();
    return 0;
}
#endif


/* second stage lexer */
int yylex(void)
{
	int token;

repeat:
	token = yylex1();

	if (prev_token == T_EOL || prev_token == T_HELPTEXT) {
		if (token == T_EOL) {
			/* Do not pass unneeded T_EOL to the parser. */
			goto repeat;
		} else {
			/*
			 * For the parser, update file/lineno at the first token
			 * of each statement. Generally, \n is a statement
			 * terminator in Kconfig, but it is not always true
			 * because \n could be escaped by a backslash.
			 */
			current_pos.file = current_file;
			current_pos.lineno = yylineno;
		}
	}

	if (prev_prev_token == T_EOL && prev_token == T_WORD &&
	    (token == T_EQUAL || token == T_COLON_EQUAL || token == T_PLUS_EQUAL))
		BEGIN(ASSIGN_VAL);

	prev_prev_token = prev_token;
	prev_token = token;

	return token;
}

static char *expand_token(const char *in, size_t n)
{
	char *out;
	int c;
	char c2;
	const char *rest, *end;

	new_string();
	append_string(in, n);

	/* get the whole line because we do not know the end of token. */
	while ((c = input()) != EOF) {
		if (c == '\n') {
			unput(c);
			break;
		}
		c2 = c;
		append_string(&c2, 1);
	}

	rest = text;
	out = expand_one_token(&rest);

	/* push back unused characters to the input stream */
	end = rest + strlen(rest);
	while (end > rest)
		unput(*--end);

	free(text);

	return out;
}

static void append_expanded_string(const char *str)
{
	const char *end;
	char *res;

	str++;

	res = expand_dollar(&str);

	/* push back unused characters to the input stream */
	end = str + strlen(str);
	while (end > str)
		unput(*--end);

	append_string(res, strlen(res));

	free(res);
}

void zconf_starthelp(void)
{
	new_string();
	last_ts = first_ts = 0;
	BEGIN(HELP);
}

static void zconf_endhelp(void)
{
	yylval.string = text;
	BEGIN(INITIAL);
}

static inline bool is_absolute(const char *path)
{
#ifndef _WIN32
        return *path == '/';
#else
	return path[0] != '\0' && path[1] == ':';
#endif
}

/*
 * Try to open specified file with following names:
 * ./name
 * $(srctree)/name
 * The latter is used when srctree is separate from objtree
 * when compiling the kernel.
 * Return NULL if file is not found.
 */
FILE *zconf_fopen(const char *name)
{
	char *env, fullname[PATH_MAX+1];
	FILE *f;

	f = fopen(name, "r");
	if (!f && name != NULL && !is_absolute(name)) {
		env = conf_getenv(SRCTREE);
		if (env) {
			snprintf(fullname, sizeof(fullname),
				 "%s/%s", env, name);
			f = fopen(fullname, "r");
		}
	}
	return f;
}

void zconf_initscan(const char *name)
{
	yyin = zconf_fopen(name);
	if (!yyin) {
		fprintf(stderr, "error: unable to find file %s\n", name);
		exit(1);
	}

	current_buf = xmalloc(sizeof(*current_buf));
	memset(current_buf, 0, sizeof(*current_buf));

	current_file = file_lookup(name);
	yylineno = 1;
}

void zconf_nextfile(const char *name)
{
	struct file *iter;
	struct file *file = file_lookup(name);
	struct buffer *buf = xmalloc(sizeof(*buf));
	memset(buf, 0, sizeof(*buf));

	current_buf->state = YY_CURRENT_BUFFER;
	yyin = zconf_fopen(file->name);
	if (!yyin) {
		fprintf(stderr, "%s:%d: error: unable to open file \"%s\"\n",
			zconf_curname(), zconf_lineno(), file->name);
		exit(1);
	}
	yy_switch_to_buffer(yy_create_buffer(yyin, YY_BUF_SIZE));
	buf->parent = current_buf;
	current_buf = buf;

	current_file->lineno = yylineno;
	file->parent = current_file;

	for (iter = current_file; iter; iter = iter->parent) {
		if (!strcmp(iter->name, file->name)) {
			fprintf(stderr,
				"error: recursive inclusion detected\n"
				"  info: inclusion path:\n"
				"    current file : %s\n", file->name);
			iter = file;
			do {
				iter = iter->parent;
				fprintf(stderr, "    included from: %s:%d\n",
					iter->name, iter->lineno - 1);
			} while (strcmp(iter->name, file->name));
			exit(1);
		}
	}

	yylineno = 1;
	current_file = file;
}

static void zconf_endfile(void)
{
	struct buffer *parent;

	current_file = current_file->parent;
	if (current_file)
		yylineno = current_file->lineno;

	parent = current_buf->parent;
	if (parent) {
		fclose(yyin);
		yy_delete_buffer(YY_CURRENT_BUFFER);
		yy_switch_to_buffer(parent->state);
	}
	free(current_buf);
	current_buf = parent;
}

int zconf_lineno(void)
{
	return current_pos.lineno;
}

const char *zconf_curname(void)
{
	return current_pos.file ? current_pos.file->name : "<none>";
}
